In [3]:
from time import process_time_ns

#列表转为ndarray
import numpy as np
list1=[1,2,3,4]
print(list1)


[1, 2, 3, 4]


In [4]:
oneArray=np.array(list1)
print(type(oneArray))
print(oneArray)

<class 'numpy.ndarray'>
[1 2 3 4]


In [5]:
import random
import time
import numpy as np

a=[]
for i in range(100000000):
    a.append(random.random())
print("随机完成")
b=np.array(a)
print("转换完成")
t1=time.time()
sum1=sum(a)
t2=time.time()
t4=time.time()
sum3=np.sum(b)
t5=time.time()
print(t2-t1,t5-t4)

随机完成
转换完成
0.3151853084564209 0.05251908302307129


In [6]:
t1=np.array([1,2,3])
print(t1)
print(type(t1))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
t2=np.array(range(10))
print(t2)
print(type(t2))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [8]:
t3=np.arange(0,10,2)
print(t3)
print(type(t3))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [9]:
import numpy as np
list2=[[1,2],[3,4],[5,6]]

twoArray=np.array(list2)
print(twoArray)
print(type(twoArray))
print(list2)

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
[[1, 2], [3, 4], [5, 6]]


In [10]:
twoArray.tolist()

[[1, 2], [3, 4], [5, 6]]

In [11]:
print(twoArray.ndim)
print(twoArray.shape)
print(twoArray.size)
print(twoArray.dtype)

2
(3, 2)
6
int64


In [12]:
four=np.array([[1,2,3],[4,5,6]])
print(four)

four1=four
print(id(four))
four.shape=(3,2)
print(id(four1))
print(id(four))
print(four)

[[1 2 3]
 [4 5 6]]
1879306152496
1879306152496
1879306152496
[[1 2]
 [3 4]
 [5 6]]


In [13]:
four2=four.reshape(2,3)
print(four)
print(id(four))
print(id(four2))
print(four2)


[[1 2]
 [3 4]
 [5 6]]
1879306152496
1879306152592
[[1 2 3]
 [4 5 6]]


In [14]:
five=four.reshape((6,),order='C')
six=four.flatten()
print(five)
print(six)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [15]:
seven=five.reshape(3,2)
seven

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
t=np.arange(24)
print(t)
print(f'shape{t.shape}')
print(t.ndim)
t1=t.reshape((4,6))
print(t1)
print(f'shape{t1.shape}')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
shape(24,)
1
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
shape(4, 6)


In [17]:
import random
f=np.array([1,2,3,4,5])
print(f.itemsize)
print(f.dtype)

8
int64


In [18]:
f1=f.astype(np.int64)
print(f1.dtype)
print(f1.itemsize)

int64
8


In [19]:
t1=np.arange(24).reshape((6,4))
t2=np.arange(100,124).reshape((6,4))
print(t1)
print(t2)
print(t1+t2)
print(t1*t2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [20]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))
print(np.sum(a))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]
21


In [21]:
a=np.arange(24).reshape((2,3,4))
b=np.sum(a,axis=1)
print(b.shape)

(2, 4)


In [22]:
a=10
b=5
c=a if a>b else b
c

10

In [23]:
score=np.array([[80,88],[82,81],[75,81]])
result=np.where(score<80,True,False)
print(result)
score[result]=100
score

[[False False]
 [False False]
 [ True False]]


array([[ 80,  88],
       [ 82,  81],
       [100,  81]])

In [24]:
t=np.arange(24).reshape(4,6)
t<10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [25]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])
print('第一个组：')
print(a)
print('\n')

print('向数组添加元素：')
print(np.append(a,[[7,8,9]],axis=0))
print('\n')
print(a)
print('-'*55)
print(np.append(a,[[5,5,5],[7,8,9]],axis=1))
print(a)
b=np.array([[7,8,9]])
print(b.ndim)
print(b)

第一个组：
[[1 2 3]
 [4 5 6]]


向数组添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2 3]
 [4 5 6]]
-------------------------------------------------------
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]]
2
[[7 8 9]]


In [26]:
res=np.maximum([-2,-1,4,1,2],[1,2,3,4,5])
print(res)

[1 2 4 4 5]


In [30]:
result=np.mean(score)
print(score)
print(result)
result=np.mean(score,axis=0)
print(result)

arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

[[ 80  88]
 [ 82  81]
 [100  81]]
85.33333333333333
[87.33333333 83.33333333]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]


In [33]:
d=np.random.random((2,4))
print(d)


[[0.22093712 0.22059714 0.53065317 0.74173399]
 [0.84663542 0.44174448 0.41889172 0.14577191]]


In [37]:
a=np.arange(16).reshape(4,4)
print(f'a:{a}')
print('分割')
b=np.vsplit(a,2)
print(b)

a:[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
分割
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
